name: CheckIn

on:
  schedule:
    - cron: "40 22 * * *" # 北京时间上午06:40
  workflow_dispatch:
jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          COOKIE__1: ${{ secrets.COOKIE__1 }}
          COOKIE__2: ${{ secrets.COOKIE__2 }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          yarn
          yarn checkin
